language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

# Specify versions of WordPress to test against
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=3.9.2 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
    - php: hhvm
      env: WP_VERSION=3.9.2 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

notifications:
  slack: aesop:GGeOu8QQeUGTkLvO1zTblBZv
