language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

# Specify versions of WordPress to test against
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.4.1 WP_MULTISITE=0
    - WP_VERSION=3.3.2 WP_MULTISITE=0
    - WP_VERSION=3.2.1 WP_MULTISITE=0 
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.4.1 WP_MULTISITE=1
    - WP_VERSION=3.3.2 WP_MULTISITE=1 
    - WP_VERSION=3.2.1 WP_MULTISITE=1
